# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
  name = "HOME"
#  pageRef = "posts"
  weight = 10

[[main]]
  name = "BIO"
  weight = 20

[[main]]
  name = "SHOWS"
#  parent = "Parent"
#  pageRef = "posts"
  weight = 30

# MEDIA acts as a dropdown parent
[[main]]
  name = "MEDIA"
  identifier = "media"
  weight = 40

  [[main]]
    parent = "media"
    name = "MUSIC"
#    pageRef = "posts"
    weight = 41

  [[main]]
    parent = "media"
    name = "GALLERY"
#    pageRef = "tags/interesting-topic"
    weight = 42

[[main]]
  name = "BOOKINGS"
#  pageRef = "categories"
  weight = 50

[[main]]
  name = "SHOP"
#  pre = "github"
#  pageRef = "categories/awesome"
  weight = 60

#[[main]]
#  name = "CONTACT US"
#  pageRef = "tags"
#  weight = 70

[[main]]
  name = "COLLECTIVE"
  identifier = "collective"
  weight = 80
  # url = "/collective/"
  # title = "Learn about the collective"

  [[main]]
    parent = "collective"
    name = "About"
    # url = "/collective/about/"
    weight = 81
    # or: pageRef = "collective/about"

  [[main]]
    parent = "collective"
    name = "What We Do"
    # url = "/collective/what-we-do/"
    weight = 82
    # or: pageRef = "collective/what-we-do"

  # Child: Workshops
  [[main]]
    parent = "collective"
    name   = "Workshops"
    # url    = "/collective/workshops/"
    weight = 83
    # or: pageRef = "collective/workshops"

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


[[footer]]
  name = "CONTACT US"
#   pageRef = "tags"
  weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20